name: flake8

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ["tm1filetools/**/*", "tests/**/*"]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: scrambldchannel/lintly-flake8-github-action@v1.1
        with:
          # The GitHub API token to create reviews with
          token: ${{ secrets.tm1filetools_TOKEN }}
          # Fail if "new" violations detected or "any", default "new"
          failIf: new
